=== jsangradorp/nikonikoapi/docs/raml/schemas/board-schema.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-03/schema",
  "$id": "schemas/board-schema.json",
  "required": true,
  "properties": {
    "boardId": {
      "type": "integer",
      "required": true
    },
    "label": {
      "type": "string",
      "required": true
    },
    "people": {
      "type": "array",
      "items": {
        "$id": "schemas/person-schema.json"
      },
      "required": false
    },
    "reportedFeelings": {
      "type": "array",
      "items": {
          "$id": "schemas/feeling-schema.json"
      },
      "required": false
    }
  }
}

=== jsangradorp/nikonikoapi/docs/raml/examples/board-example.json
{
  "boardId": 1,
  "label": "Los Marianos",
  "people": [
    {
      "personId": 1,
      "label": "Mariano"
    },
    {
      "personId": 2,
      "label": "Herminia"
    }
  ],
  "reportedFeelings": [
    {
      "date": "2017-05-27",
      "reportedFeelings": [
        {
          "personId": 1,
          "feeling": "bad"
        },
        {
          "personId": 2,
          "feeling": "neutral"
        }
      ]
    },
    {
      "date": "2017-05-26",
      "reportedFeelings": [
        {
          "personId": 1,
          "feeling": "neutral"
        },
        {
          "personId": 2,
          "feeling": "good"
        }
      ]
    }
  ]
}
